### ISSUE TITLE
插件初始化函数失效

### ISSUE THREAD

**Issue by BalconyJH** [BalconyJH/nonebot_plugin_valorant#4]

**Comment by PackageInstaller** [comment]
![image](https://github.com/BalconyJH/nonebot_plugin_valorant/assets/80018096/9a43c182-d2fb-4518-a680-3523068130b8)
缺少依赖，尝试使用pip install 安装依赖，但是都不存在，请问依赖到底是？
![image](https://github.com/BalconyJH/nonebot_plugin_valorant/assets/80018096/7e9222ee-a354-4631-bfda-3fcccf63d7ee)

**Comment by BalconyJH** [comment]
我考试周，先过完这两周再说
